repos:
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        entry: cargo fmt --all -- --check
        language: system
        pass_filenames: false
      # - id: clippy
      #   name: clippy
      #   entry: cargo clippy --all-targets --all-features #-- -D warnings
      #   language: system
      #   pass_filenames: false
      # - id: cargo-check
      #   name: cargo check
      #   entry: cargo check --all-targets --all-features
        # language: system
        # pass_filenames: false
      # - id: cargo-test
      #   name: cargo test (smoke)
      #   entry: cargo test -- --quiet --skip slow
      #   language: system
      #   pass_filenames: false
