[package]
name = "meta-forge"
version = "0.1.0"
edition = "2021"
authors = ["Mladen Rasic <youremail@example.com>"]
description = "Metagenomic data analysis and LLM integration toolkit"
license = "MIT"
repository = "https://github.com/mladen5000/meta-forge"
readme = "README.md"

[[bin]]
name = "meta-forge"
path = "src/main.rs"

[[bin]]
name = "test-paired-reads"
path = "src/bin/test_paired_reads.rs"

[[bin]]
name = "demo-progress"
path = "src/bin/demo_progress.rs"

[[bin]]
name = "integrated-demo"
path = "src/bin/integrated_demo.rs"

[lib]
name = "meta_forge"
path = "src/lib.rs"

[dependencies]

# --- Core Data Structures & Concurrency ---
ahash = { version = "0.8.12", features = ["serde"] }
dashmap = "6.1.0"
fxhash = "0.2.1"
parking_lot = "0.12.4"

# --- Configuration, CLI, and Utilities ---
clap = { version = "4.5.42", features = ["derive"] }
config = "0.15.13"
toml = "0.8.10"
dirs = "5.0.1"
num_cpus = "1.16.0"
tempfile = "3.20.0"

# --- Performance, Compression, Parallelism ---
criterion = { version = "0.7.0", optional = true }
lz4_flex = "0.11.5"
rayon = "1.10.0"
tokio = { version = "1.41.1", features = ["full"] }
crossbeam-channel = "0.5.15"
memmap2 = "0.9.5"
mimalloc = "0.1.47"

# --- ML/AI & Scientific Computing ---
candle-core = "0.9.1"
candle-nn = "0.9.1"
ndarray = { version = "0.16.1", features = ["serde"] }
ort = "1.16.3"
petgraph = "0.8.2"
smartcore = "0.4.2"
fastrand = "2"
pathfinding = "4.12.0"

# --- Error Handling, Logging, Observability ---
anyhow = "1.0.98"
thiserror = "2.0.12"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing-appender = "0.2.3"

# --- Bioinformatics ---
bio = "2.3.0"
seq_io = "0.3.4"
rust-htslib = "0.48.0"

# --- Database & Serialization ---
rusqlite = { version = "0.37.0", features = ["chrono"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.107"
proptest = "1.7.0"
bincode = "1.3.3"
chrono = { version = "0.4.38", features = ["serde"] }

# --- Probabilistic Data Structures ---
probabilistic-collections = "0.7.0"
hyperloglog = "1.0.1"
# sketchy = "0.3.0"  # Package not available, removing for now

[features]
# Optional/benchmarking features
bench = ["criterion"]

[dev-dependencies]
criterion = "0.7.0"
