[package]
name = "meta-forge"
version = "0.1.0"
edition = "2024"
authors = ["Mladen Rasic <youremail@example.com>"]
description = "Metagenomic data analysis and LLM integration toolkit"
license = "MIT"
repository = "https://github.com/mladen5000/meta-forge"
readme = "README.md"

[dependencies]

# --- Core Data Structures & Concurrency ---
ahash = "0.8.12"
dashmap = "6.1.0"
parking_lot = "0.12.4"

# --- Configuration, CLI, and Utilities ---
clap = "4.5.42"
config = "0.15.13"
tempfile = "3.20.0"

# --- Performance, Compression, Parallelism ---
criterion = { version = "0.7.0", optional = true }
lz4_flex = "0.11.5"
rayon = "1.10.0"

# --- ML/AI & Scientific Computing ---
candle-core = "0.9.1"
ndarray = "0.16.1"
ort = "1.16.3"
petgraph = "0.8.2"
smartcore = "0.4.2"

# --- Error Handling, Logging, Observability ---
anyhow = "1.0.98"
thiserror = "2.0.12"
tracing = "0.1.41"

# --- Bioinformatics ---
bio = "2.3.0"

# --- Database & Serialization ---
rusqlite = "0.37.0"
serde = { version = "1.0.219", features = ["derive"] }

[features]
# Optional/benchmarking features
bench = ["criterion"]

[dev-dependencies]
criterion = "0.7.0"
