# Default Configuration for Metagenomics Pipeline

[general]
name = "metagenomics-pipeline"
version = "1.0.0"
work_dir = "./work"
temp_dir = "./tmp"
output_dir = "./output"
debug_mode = false

[assembly]
k_min = 15
k_max = 31
min_coverage = 2
complexity_threshold = 0.7
enable_simplification = true

[assembly.bubble_popping]
enabled = true
max_bubble_length = 1000
min_coverage_ratio = 0.1

[assembly.tip_removal]
enabled = true
max_tip_length = 100
min_coverage_ratio = 0.1

[features]
sequence_feature_dim = 100
graph_feature_dim = 50
kmer_feature_dim = 64
include_composition = true
include_codon_usage = true
include_patterns = true
include_complexity = true
include_topology = true
include_centrality = false
include_clustering = true
kmer_sizes = [3, 4, 5, 6]
max_kmers = 10000

[database]
db_path = "./data/metagenomics.db"
enable_wal_mode = true
cache_size = 10000
enable_foreign_keys = true
batch_size = 1000
enable_compression = true
cache_memory_limit_mb = 256

[database.auto_vacuum]
enabled = true
threshold_mb = 100
schedule = "0 2 * * *"

[ml]
taxonomy_model_path = "./models/taxonomy.onnx"
repeat_model_path = "./models/repeat_resolution.onnx"
error_correction_model_path = "./models/error_correction.onnx"

[ml.training]
batch_size = 32
learning_rate = 0.001
epochs = 100
validation_split = 0.2
early_stopping_patience = 10

[ml.inference]
batch_size = 16
confidence_threshold = 0.8
use_gpu = false
max_sequence_length = 10000

[performance]
num_threads = 8                 # 0 = auto-detect
memory_limit_gb = 8
enable_memory_monitoring = true
streaming_buffer_size = 1000
chunk_size = 100
enable_compression = false

[performance.monitoring]
enabled = true
sample_interval_ms = 1000
alert_memory_threshold_percent = 90.0
alert_cpu_threshold_percent = 85.0

[logging]
level = "info"
format = "pretty"
enable_performance_logging = true
enable_metrics = true

[io]
supported_input_formats = ["fasta", "fastq", "fasta.gz", "fastq.gz"]

[io.output_formats]
fasta = true
fastq = false
gfa = true
json = true
tsv = true
html_report = true

[io.file_handling]
enable_memory_mapping = true
buffer_size = 8192
max_file_size_gb = 10
compression_level = 6
